### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by ziceptor** [JamieS1211/MineReset#2] opened 2018-03-26 17:53 UTC
Is displayed in the message %mine% https://i.imgur.com/f8aOhLe.png
Config https://gist.github.com/ziceptor/244301bc151942d3a0c976e9cf931725

You must also add a translation for "seconds" and other.
https://github.com/JamieS1211/MineReset/blob/1d846530b5dd51e5e3e04e85525fbc7b462e4436/src/main/java/com/github/jamies1211/minereset/SecondsToString.java

**Comment by JamieS1211** [comment] 2018-03-26 19:17
Hi, firstly thanks for the issue. At the moment I am not at my main workstation with code etc. just mobile but I will try to help.

For your issues where "%mine%" is showing up, I had a little look in the code and found that at lines 502 and 510 the replacement string is "%mines%" so if you change what is in your translation file to "%mines%" hopefully that will be fixed.

For the issue where seconds minutes and hours are not translated, that is 100% my fault, they were not stored in the message file so I didn't add them to config and completely forgot about them. I should have time to sort this issue tomorrow and will release an update adding those to the config.

Finally, is this translation Russian? I hope I haven't offended you but I don't know many languages and it seems like the Russian alphabet. Either way how would you feel about me adding this message.conf file of yours to be able to be downloaded from the main sponge page and the releases list? I would love to try and get as many languages as possible available to users.

**Comment by ziceptor** [comment] 2018-03-26 19:22
Not hurry. It can wait. Thx.

**Comment by JamieS1211** [comment] 2018-03-26 19:58
No worries, did changing "%mine%" to "%mines%" work?

**Comment by ziceptor** [comment] 2018-03-27 01:38
It's not working

**Comment by JamieS1211** [comment] 2018-03-27 15:10
Hi, I have updated the plugin and it should now allow you to edit the time units. Can you please link me a copy of your messages config so I can have a closer look and try work out why you are having an issue.

**Comment by JamieS1211** [comment] 2018-03-27 15:20
I believe I have found the issue causing this and fixed it, releasing another new version (1.0.11). Could you please confirm that everything is working for you in the new version? Also are you interested in sharing your translation for the project?

**Comment by ziceptor** [comment] 2018-03-27 17:18
Works, but not everywhere.

actionbar https://i.imgur.com/2teqWIk.png
fillblock https://i.imgur.com/3nvG7cS.png

I would like to be able to change the meaning %mine%. To set a meaningful name for the mine.
It is possible to enter an additional key into the config:

```
"4 - MineGroups" {
    GROUP {
        ZIMINE {
           DysplayName="Заброшенная шахта"
```
Output %mine%=DysplayName

> Also are you interested in sharing your translation for the project?

I didn't plan on doing a full translation. Only messages for the players. If I have time, I'll translate. I will remember your request.

**Comment by ziceptor** [comment] 2018-03-27 17:22
At each filling

` [Mines] ERROR 26errors occurred when filling the mine. Check the mine config and make sure all blocks are on the server`

Config https://gist.github.com/ziceptor/f5f9a290d8bce5ef18a2a878e116e23e

**Comment by JamieS1211** [comment] 2018-03-28 12:54
I have found the cause of your problem. The dirt.

You have: `minecraft:dirt`
You need to have `minecraft:dirt[snowy=false,variant=dirt]`

I have checked, title, action-bar and chat and can't find where the messages are displaying incorrectly in 1.0.11.

I will look into making a display name for mines. This was intended to be the mine name but after some testing it appears there may be issues when typing commands in other alphabets as shown in the image below.

![image](https://user-images.githubusercontent.com/8209033/38030077-86988564-328f-11e8-8ea1-4c720687c402.png)

**Comment by ziceptor** [comment] 2018-03-28 13:40
%mine%:
  Video https://youtu.be/usAGgg7eAFA
  Picture https://i.imgur.com/8VG5D6E.png

1.0.11 for api7: https://i.imgur.com/XqZvdmV.png

**Comment by JamieS1211** [comment] 2018-03-28 14:17
I can't actually reproduce this. Yeah that 1.0.11 is the one for API 7. Could you stop server. Re-download and place in 1.0.11 and then restart. If you still get the errors can you then send me your messages and mines config.

**Comment by ziceptor** [comment] 2018-03-28 15:12
configs https://cloud.mail.ru/public/7Tre/mQurF2cnR

**Comment by ziceptor** [comment] 2018-03-28 15:16
Pay attention to the time.. there are no spaces. Although you fixed it. I downloaded the source code and built the jar. Nothing has changed. https://i.imgur.com/sP4mRWU.png

**Comment by ziceptor** [comment] 2018-03-28 15:23
I understood. You have used `%mine%` and `%mines%`. You mentioned it above. :)

**Comment by ziceptor** [comment] 2018-03-28 15:40
Hope you don't forget about it:
I would like to be able to change the meaning %mine%. To set a meaningful name for the mine.
It is possible to enter an additional key into the config:

"4 - MineGroups" {
    GROUP {
        ZIMINE {
           DysplayName="Заброшенная шахта"

Output %mine%=DysplayName

**Comment by JamieS1211** [comment] 2018-03-28 16:28
Ok, I will have a look again. There is no space intended between the number and the time unit as this is the say I consider it correct to type. The issue I fixed regarding that was spaces before a time unit if the previous time unit was 0.

I have found why your messages are not always working. In some cases its %mines% and others its %mine% based on if 1 or more are being reset. The settings "resettingNowPlural" and "willResetIn" should be %mines% and that should fix the problem. As far as this issue goes I will try and update the code so it will allow either in future versions and this will come when I release the display name of a mine.

**Comment by ziceptor** [comment] 2018-03-28 18:15
Let the user decide how to format the output. It would be right for me: 2 секунды (2 seconds).
Wrong: 2секунды

**Comment by JamieS1211** [comment] 2018-03-28 18:25
If you want to change how its formatted you can. Put quotes around your time units and then a space before the unit like this:

![image](https://user-images.githubusercontent.com/8209033/38048611-c6a4d8a0-32bd-11e8-8a2d-8359e6526784.png)


I am just finishing up some stuff to implement display names

**Comment by ziceptor** [comment] 2018-03-28 18:38
Thx. How to control the length of time a message is displayed in actionbar?

**Comment by JamieS1211** [comment] 2018-03-28 19:04
As far as I know it isn't possible to control the length of time a message is in the action bar directly. Hence the only way it would be possible would be to send a blank message after to clear the current message or send the same message many times. Either way I think this would be quite messy so don't plan on implementing it as of now.

**Comment by ziceptor** [comment] 2018-03-28 19:48
See how this is implemented in this plugin https://github.com/rojo8399/TitleMOTD

**Comment by JamieS1211** [comment] 2018-03-29 11:33
https://bugs.mojang.com/browse/MC-106167

So by the looks of this the action bar does not behave correctly but this is working for the main title (huge messages)

**Comment by JamieS1211** [comment] 2018-05-01 11:54
I have implemented this however it only correctly affects the title. The action bar (small text above the item hotbar) is not able to be affected at the moment.

**Closed as completed by JamieS1211** 2018-05-01 11:54 UTC
